### ISSUE TITLE
build with npm linked dev-dependencies

### ISSUE THREAD

**Issue by cruzanmo** [nymag/clay-kiln#634]
When npm-linking a dependency, e.g. `npm link medium-editor`, the webpack build does not find the package.

Per [webpack's suggestion](https://webpack.github.io/docs/troubleshooting.html#npm-linked-modules-don-t-find-their-dependencies) attempted adding the following code to the config:

```
  resolve: { fallback: path.join(__dirname, 'node_modules') },
  resolveLoader: { fallback: path.join(__dirname, 'node_modules') }
```

However, still get an error on build:

```
ERROR in ../medium-editor/dist/js/medium-editor.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/mcroney/_dev/medium-editor/dist/js"
    at /Users/mcroney/_dev/clay-kiln/node_modules/babel-core/lib/transformation/file/options/option-manager.js:281:17
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/mcroney/_dev/clay-kiln/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
    at OptionManager.mergePresets (/Users/mcroney/_dev/clay-kiln/node_modules/babel-core/lib/transformation/file/options/option-manager.js:254:10)
    at OptionManager.mergeOptions (/Users/mcroney/_dev/clay-kiln/node_modules/babel-core/lib/transformation/file/options/option-manager.js:239:14)
    at OptionManager.init (/Users/mcroney/_dev/clay-kiln/node_modules/babel-core/lib/transformation/file/options/option-manager.js:338:12)
    at File.initOptions (/Users/mcroney/_dev/clay-kiln/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/mcroney/_dev/clay-kiln/node_modules/babel-core/lib/transformation/file/index.js:137:24)
    at Pipeline.transform (/Users/mcroney/_dev/clay-kiln/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/mcroney/_dev/clay-kiln/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/mcroney/_dev/clay-kiln/node_modules/babel-loader/index.js:131:12)
 @ ./behaviors/wysiwyg.js 5:19-43
```

**Comment by nelsonpecora** [comment]
Interesting! We should fix this.

**Comment by nelsonpecora** [comment]
This seems to be working now in kiln 1.0
